#!/usr/bin/python

# Copyright (C) 2006-2015 Avencall
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

import sys

from xivo_confd_client import Client

client = Client("localhost", https=False, port=9487)


def get_voicemail(number, context):
    response = client.voicemails.list(search=number)

    found = [v for v in response['items']
             if v['number'] == number and v['context'] == context]

    assert len(found) > 0, "voicemail {}@{} not found!".format(number, context)
    assert len(found) == 1, "more than one voicemail found when searching for {}@{}".format(number, context)
    return found[0]


def update_password(voicemail, new_password):
    voicemail['password'] = new_password
    client.voicemails.update(voicemail)


if __name__ == "__main__":
    if len(sys.argv) != 4:
        raise ValueError("Missing args!")

    context = sys.argv[1]
    number = sys.argv[2]
    new_password = sys.argv[3]

    voicemail = get_voicemail(number, context)
    update_password(voicemail, new_password)
