#!/usr/bin/python

# Copyright (C) 2006-2015 Avencall
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

import os
import sys

from xivo_confd_client import Client

DEFAULT_CONFD_CONFIG = {'host': 'localhost',
                        'port': 9487,
                        'https': 'False'}

def get_confd_client_config():
    host = os.environ.get('CONFD_HOST', DEFAULT_CONFD_CONFIG['host'])
    port = int(os.environ.get('CONFD_PORT', DEFAULT_CONFD_CONFIG['port']))
    https = os.environ.get('CONFD_HTTPS', DEFAULT_CONFD_CONFIG['https']).lower() == 'true'
    username = os.environ.get('CONFD_USERNAME')
    passwd = os.environ.get('CONFD_PASSWORD')

    config = {'host': host,
              'port': port,
              'https': https}
    if username:
        config['username'] = username
    if passwd:
        config['password'] = passwd

    return config

def get_voicemail(client, number, context):
    response = client.voicemails.list(search=number)

    found = [v for v in response['items']
             if v['number'] == number and v['context'] == context]

    assert len(found) > 0, "voicemail {}@{} not found!".format(number, context)
    assert len(found) == 1, "more than one voicemail found when searching for {}@{}".format(number, context)
    return found[0]


def update_password(client, voicemail, new_password):
    voicemail['password'] = new_password
    client.voicemails.update(voicemail)


if __name__ == "__main__":
    if len(sys.argv) != 4:
        raise ValueError("Missing args!")

    context = sys.argv[1]
    number = sys.argv[2]
    new_password = sys.argv[3]

    confd_client_config = get_confd_client_config()
    client = Client(**confd_client_config)

    voicemail = get_voicemail(client, number, context)
    update_password(client, voicemail, new_password)
