#!/usr/bin/python

# Copyright (C) 2006-2015 Avencall
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

import sys

from xivo_dao.data_handler.voicemail import services as voicemail_services
from xivo_dao.data_handler.user_voicemail import services as user_voicemail_services
from xivo_dao.data_handler.user_voicemail.model import UserVoicemail

if len(sys.argv) != 4:
    raise ValueError("Missing args!")

context = sys.argv[1]
mailbox = sys.argv[2]
new_password = sys.argv[3]

# Currently, we need to unlink the voicemail from the user before editing it.
voicemail = voicemail_services.get_by_number_context(mailbox, context)
old_user_voicemail = user_voicemail_services.find_by_voicemail_id(voicemail.id)
user_voicemail_services.dissociate(old_user_voicemail)

voicemail = voicemail_services.get_by_number_context(mailbox, context)
voicemail.password = new_password
voicemail_services.edit(voicemail)

# Relink the user to the voicemail
new_user_voicemail = UserVoicemail(user_id=old_user_voicemail.user_id,
                                   voicemail_id=old_user_voicemail.voicemail_id,
                                   enabled=old_user_voicemail.enabled)

user_voicemail_services.associate(new_user_voicemail)
